### ISSUE TITLE
Packets should have validation checks

### ISSUE THREAD

**Issue by RavenX8** [dev-osrose/osIROSE-new#103]
Packets should have some standard way of checking to see if the range of values in the data are valid. This way before even attempting to process the packet, we can do some pre-checking to verify if it isn't a garbage packet.

**Comment by L3nn0x** [comment]
The new packets check if there is enough space to read/write the buffer. to have proper ranges, we'll need to update the DSL.

**Comment by RavenX8** [comment]
What about the check to see `my current data size`? Like it would be nice if we could have a compiler time check to make sure the sizes don't change on data change

**Comment by L3nn0x** [comment]
What do you mean? I was thinking of adding a range to a variable, something like uint8_t serverType [0..3], which would indicate that the variable serverType can only take the values 0, 1 2 or 3.

**Comment by RavenX8** [comment]
Like, if I change the type of the type of a var in a class from a uint8_t to a uint64_t, it SHOULD not change the size of the data sent out unless I change the packet. We should have checks at compile time to ensure that the packet size sent out is the same. That is what the issue was with the character data packet. A type was changed from uint16_t to a std::chrono::duration which then changed the size of the packet.

**Comment by L3nn0x** [comment]
Yes, that's a good idea and I already have it in the new packet system. Got bitten once, not twice.
I was thinking of adding more constraining checks. something like: `double[-10000.f,10000.f] y;` would mean that y should be between -1000 and 1000. I don't know if it's something we want, but it can be done.

**Comment by L3nn0x** [comment]
This is done with the newest packet system
