### ISSUE TITLE
Incorrect Password - SHA2 + SALT coverter

### ISSUE THREAD

**Issue by wouthuib** [dev-osrose/osIROSE-new#118]
With the latest code I am unable to find the right combination to store a proper username and password in the MySQL database without getting an "inccorect password" error in my client. 

All tutorials mention MD5 encryption, but obviously this is not in use anymore and I cannot find an up to date tutorial how to register new users with the right password.

The LoginServer accepts the connection but I do not find any details on the Server about wrong passwords applied. So perhaps an additional console line with "wrong password applied" would also be convenient.

Please advise. and Thanks in advance! :-)

Regards,
Wouter

**Comment by RavenX8** [comment]
Please see procedure [`create_account`](https://github.com/dev-osrose/osIROSE-new/blob/trunk/Database/osirose.sql#L393) in the database. 

The password stored in the DB is the MD5 hash + the salt then ran through SHA2.

Edit:
You can also look at [`user_login`](https://github.com/dev-osrose/osIROSE-new/blob/trunk/Database/osirose.sql#L631) to see what we do with the MD5 hash we get from the client.

**Comment by wouthuib** [comment]
thanks it works. 

Within the MySQL database I forgot to grant privileges to call the functions and procedures to my DB user.

Thanks for your quick response.

**Comment by L3nn0x** [comment]
Also, you can activate an option in the config file that will allow you to create the account if failing to login in the client (so you'd just have to login twice and the account will get created for you).

**Comment by L3nn0x** [comment]
Closing as solved
