### ISSUE TITLE
CharServer crash broken pipe

### ISSUE THREAD

**Issue by wouthuib** [dev-osrose/osIROSE-new#119]
After connecting with the LoginServer, creating a character and entering the ROSE world I was able to walk a bit and then had some lag spikes. After a period of time the CharServer crashed and I was disconnected from game.

Console message of the CharServer is:
ProcessSend: async_write returned an error sending the packet. 32: Broken pipe

I also noticed that the ROSE world is empty. No NPC's, no monsters and no warp portals.

Do I miss a step in the installation? please advise.

Thanks and regards,
Wouter

**Comment by RavenX8** [comment]
What OS are you running the servers on? Did you compile the source yourself? If you are running on linux and compiled trunk branch, a .dmp file should have been created in `/tmp/dumps/` which gives info on why it crashed. 

No you did not miss a step. Currently NPCs, monsters and the warp portals are being worked on. The server you are using is the current rewrite of the [`old servers`](https://github.com/dev-osrose/osIROSE-new/releases/tag/v1.87.0])

**Comment by L3nn0x** [comment]
How long did it take for the server to crash? Was there any other messages from the char server before the broken pipe ?

Also, which branch of the github project are you using? trunk?

**Comment by wouthuib** [comment]
Yes so basically i use git close to get the trunk version of osirose. After that I ran the Unix environment shell script and used the make command to compile and build the source.

Database is filled with mysql -u root -p osirose < Osirose.sql

Eventually opened a tmux session for each server login, char and map. They all startup succesfully from the build folder with ./bin/LoginServer etc.

The server.json is created in which i have entered the mysql database and User credentals. All okay.

However i cannot find a tmp/dump file. 

Login works. Character creation works. But then the broken pipe errors occur and the mapserver id very slow. Also all maps are empty. Please help me out at this point.

Thanks :-)

**Comment by L3nn0x** [comment]
Maps are empty because we haven't implemented npcs nor monsters. It's coming soon!

First, did you install the patch we provide on the release page? We had to modify a little the client to be able to send packets.

When running the integration tests, nothing comes up on trunk. I'll keep looking.

**Comment by RavenX8** [comment]
I have resolved this broken pipe issue. I had lowered the timeout timer but forgot to update the STAY_ALIVE timer so the servers weren't refreshing their connections. This change is currently on the node_server branch.

**Comment by L3nn0x** [comment]
Cool, I was wondering why I didn't find anything. I must be working on an old fork of trunk. This is gonna be a pain to merge back now that I think about it...

Closing as it is solved on the node_server branch. Please tell us if there's still a bug!
