### ISSUE TITLE
Server select doesn't work as expected

### ISSUE THREAD

**Issue by RavenX8** [dev-osrose/osIROSE-new#138]
**Describe the bug**
If you use the local IP address for the ISC servers, the login server will attempt to send a client that connected from an external IP to the local IP address.

**Steps To Reproduce**
1. Change the ISC server addresses to 127.0.0.1
2. Change the Listen IP address to your public IP.
3. Start the login, character and map on the same computer
4. Launch a client that connects to your public IP.
5. Login and select the server.
6. Client fails to connect to the character server because the Login Server sent 127.0.0.1 as the IP address

**Expected behavior**
I expected to get to the character select screen with my characters

**Desktop (please complete the following information):**
 - OS: both linux and windows

**Additional context**
This issue can be fixed by storing the public IP addresses that the servers are listening on in the DB. We need this to be able to support the node server, to support having dedicated server hardware per server and support docker.

**Comment by L3nn0x** [comment]
Are you sure about this? I run the 3 servers on my laptop and connect from my desktop and it works perfectly.
Have you tried updating https://github.com/dev-osrose/osIROSE-new/blob/trunk/src/core/include/config.h#L75 with the external ip address?

**Comment by RavenX8** [comment]
If you don't have that as an external or lan ip address, you wouldn't even be able to connect to it. I'm 100% sure this is a bug because I checked the packet data and it did send the private ip address

**Comment by RavenX8** [comment]
I tested this again and I wasn't able to get it to happen again.

Putting this in the backlog

**Comment by L3nn0x** [comment]
Solved
