### ISSUE TITLE
Character creation

### ISSUE THREAD

**Issue by RavenX8** [dev-osrose/osIROSE-new#14]
The character server (and map server) needs the structures/classes created for holding character data. This would include inventory, stats, skills, and quest structs. We will also need a way to serialize the data to a database or file.
- [x] Basic character data (stats, looks)
- [x] Inventory
- [x] Skills
- [x] Quests (Do not need to make them work, just the data)
- [x] Load from database
- [x] Save into database

**Comment by L3nn0x** [comment]
part of the character is saved back to the database.
For now, only the position is saved back.

**Comment by L3nn0x** [comment]
Everything except quest data, hotbar, status effect, riding items, bullet items and skills are now synced from and to the database.

**Comment by RavenX8** [comment]
Remember, quest data only needs to have the structures there. We don't need to load anything for this issue to be closed.

**Comment by L3nn0x** [comment]
Yeah, I'm thinking if I should write a nice struct or go with the current implementation (triggers & stuff)
