### ISSUE TITLE
[Mapserver] Lua scripts failing to load

### ISSUE THREAD

**Issue by rminderhoud** [dev-osrose/osIROSE-new#146]
**Describe the bug**
Compiling the latest trunk with GCC and Make, running the mapserver triggers a huge number of script errors.

Example:
```
[17:11:37.960 +05:00] [E] [server] Error (re)loading lua scripts 'scripts/npcs/ai/[ferrell_guild_staff]_rooen.lua' : sol: runtime error: scripts/npcs/ai/[ferrell_guild_staff]_rooen.lua:1: attempt to index a function value (global 'npc')
stack traceback:
	scripts/npcs/ai/[ferrell_guild_staff]_rooen.lua:1: in main chunk
	[C]: in function 'include'
	scripts/npc_scripts.lua:461: in main chunk
	[C]: in function 'include'
	scripts/root.lua:1: in main chunk 

```
**Steps To Reproduce**
1. Clone latest master
2. Build
3. Run `MapServer`

**Expected behavior**
Mapserver should start without errors

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
[err.txt](https://github.com/dev-osrose/osIROSE-new/files/2619847/err.txt)

**Comment by L3nn0x** [comment]
@RavenX8 please don't push to trunk directly without testing :)

**Comment by rminderhoud** [comment]
Commenting out the npc behavior fixes it:

```lua
-- include("npc_scripts.lua");
include("npc_spawns.lua");
```

**Comment by RavenX8** [comment]
this isn't actually an error. this is a warning mislabeled as an error. Anyway all it was, was that I forgot to `do npc = {}` in the `npc_scripts.lua` file.
