### ISSUE TITLE
Birth Island doesn't have respawn points

### ISSUE THREAD

**Issue by RavenX8** [dev-osrose/osIROSE-new#201]
**Describe the bug**
On birth island, there are no spawn points defined. Because of this, when you create a character, the server defaults to psoition 0,0.

**Steps To Reproduce**
Create a character that will spawn in birth island and select it

**Expected behavior**
That the new character will spawn on birth island in the place that is expected from where I selected my gemstone.

**Desktop (please complete the following information):**
all verisons

**Comment by iT0xic** [comment]
I think you can close this issue :3
