### ISSUE TITLE
loadModel failed. already exists

### ISSUE THREAD

**Issue by h2oiswater** [dev-osrose/osIROSE-new#232]
**Describe the bug**
We built server code and run server successed.
Then use client 112_112NA.
Login in game, then alert "loadModel failed. already. exists" like the picture below.

![12551607261017_ pic_hd](https://user-images.githubusercontent.com/5397807/101312191-18f2aa00-388e-11eb-930d-95729da47514.jpg)
![12561607261035_ pic_hd](https://user-images.githubusercontent.com/5397807/101312198-1bed9a80-388e-11eb-8e90-71d9a4cafa7f.jpg)

**Comment by L3nn0x** [comment]
Should be resolved, let us know if anything's amiss
