### ISSUE TITLE
Chatting system

### ISSUE THREAD

**Issue by RavenX8** [dev-osrose/osIROSE-new#40]
- [x] Normal
- [x] Shout
- [x] Whispers
- [x] Broadcast
- [x] Party

**Comment by L3nn0x** [comment]
whisper as per #71 and #69 has been implemented.

**Comment by rminderhoud** [comment]
Broadcast is for the whole server? Should it be restricted to certain access levels?

**Comment by L3nn0x** [comment]
I think it should be the whole server for now. All maps.

**Comment by L3nn0x** [comment]
Done
