### ISSUE TITLE
Clean up user sessions

### ISSUE THREAD

**Issue by RavenX8** [dev-osrose/osIROSE-new#47]
We need a way to remove sessions from the session table. It should happen automatically when a client disconnects but it should also be cleaned on a fresh boot.

**Comment by RavenX8** [comment]
Not exactly sure how this is going to work correctly.

**Comment by L3nn0x** [comment]
How about we assume that if a loginClient connects and there is no other isc server up, it is a fresh boot?

When a client disconnects in a server (apart from the map server), we can transmit a packet with the id of the client. If the client doesn't connect in a definite amount of time in the next server (so char server for the login server and map server for the char server), then we can clean its session.

When a client disconnects in the map server using the disconnect packet, the map server cleans the session. If a client crashes, the map server doesn't clean the session, and the login server can pick it up again and use it if the client re-connects.

**Comment by L3nn0x** [comment]
Implemented as per #112
