### ISSUE TITLE
Command line settings

### ISSUE THREAD

**Issue by RavenX8** [dev-osrose/osIROSE-new#55]
It would be nice to be able to start up the servers with command line settings. This would allow us to override server settings without changing the config file and such.

**Comment by RavenX8** [comment]
a lot of this is implemented. This may be already finished, just need to make sure we covered everything

**Comment by L3nn0x** [comment]
Can we close this issue?

**Comment by RavenX8** [comment]
Did we cover everything?

**Comment by L3nn0x** [comment]
I haven't checked, we might need some additional settings.

**Comment by L3nn0x** [comment]
After verification, I think we have the most important settings on the command line. Closing
