### ISSUE TITLE
Build failing due to too much memory usage during compile time

### ISSUE THREAD

**Issue by RavenX8** [dev-osrose/osIROSE-new#79]
Due to the massive usage of templates, the travis build keeps failing because we are using so much memory in the later build projects.

I have determined that the cause is that the map server includes and builds EVERY packet that the game can use when it only needs a subsection of them. Each cpp file should only include the packet headers it needs instead of including all of them. Doing this will increase build speed.

While we are at it, we should also change the headers to use as much forward declarations as possible to further increase build speed and lower memory usage.

**Comment by L3nn0x** [comment]
my latest build uses 700M per compilation thread max.

**Comment by L3nn0x** [comment]
forward declaration is used already, and there is no single header file anymore.
