### ISSUE TITLE
Rewrite Thread Pools

### ISSUE THREAD

**Issue by RavenX8** [dev-osrose/osIROSE-new#88]
I need to rewrite the thread pool class so we can use it for more then just the networking. Also we need it rewritten so it will be API independent.

**Comment by L3nn0x** [comment]
Can we close it? The new network code works from what I can tell.

**Comment by RavenX8** [comment]
it does work but the problem I have is that it still relies on ASIO. I need to split that out of the base network thread pool.

**Comment by L3nn0x** [comment]
Ok

**Comment by L3nn0x** [comment]
What's the update on this? The current codebase looks good to me.
