### ISSUE TITLE
Rewrite the database

### ISSUE THREAD

**Issue by L3nn0x** [dev-osrose/osIROSE-new#89]
Use sqlpp11 to make it easier to use the database.

- [x] Add sqlpp11
- [x] Implement the current osirose database as a c++ file
- [x] Rewrite the idatabase class (remove?)
- [x] Rewrite the irow class (remove?)
- [x] Rewrite the CMySQL_row class (remove?)
- [x] Rewrite the CMySQL_database class (remove?)
- [x] Rewrite the idatabase_pool
- [x] Rewrite the cmysql_databasepool class (remove?)
- [x] Rewrite the idatabasepoolfactory & idatabasepoolabstractfactory (remove?)

**Comment by RavenX8** [comment]
Are we able to close this?

**Comment by L3nn0x** [comment]
Yup
