### ISSUE TITLE
Map server crashes when a client login again

### ISSUE THREAD

**Issue by L3nn0x** [dev-osrose/osIROSE-new#95]
The entityX frameworks throws an assertion when trying to access a component after the character is loaded in memory. The error is Entity::component<BasicInfo>() assertion 'valid()' failed.
Is it an entityX bug? Or is it from us.

**Comment by L3nn0x** [comment]
This might be because of how we handle the deletion of entities & CMapClients. Right now, the deletion is in two times (first the entity then the client). That part needs to be rewritten to have something cleaner and less error prone.

**Comment by RavenX8** [comment]
Is this still an issue?

**Comment by L3nn0x** [comment]
I think so, I haven't had time to look into it yet, and I don't think the modifications I did helped much in that regard.

**Comment by L3nn0x** [comment]
solved as per #110
